### ISSUE TITLE
Missing G_2 subgroup checks

### ISSUE THREAD

**Issue by daira** [matter-labs/Groth16BatchVerifier#2]
The implementation in https://github.com/matter-labs/Groth16BatchVerifier/blob/master/BatchedSnarkVerifier/contracts/BatchVerifier.sol doesn't appear to do any G<sub>2</sub> subgroup checks. See appendix B.2 of the Zcash Protocol Specification for the required checks.

**Comment by shamatar** [comment]
Good evening, @daira 

Subgroup check is handled by Ethereum precompile in this case. We've explicitly checked Go implementation (in go-ethereum) and Rust (in parity, based on Sean's "bn" crate), both of them check for a valid subgroup during point parsing.

Sincerely, Alexander
